force-app/main/asyncActionSimple/objects/Async_Action__e/Async_Action__e.object-meta.xml
<CustomObject>
    <label>AsyncAction</label>
    <pluralLabel>AsyncActions</pluralLabel>
</CustomObject>

force-app/main/asyncActionSimple/objects/Async_Action__e/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/asyncActionSimple/objects/Async_Action__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/asyncActionSimple/classes/AAS_AsyncActionUtils.cls
/**
 * @description Contains service logic for the Async Action functionality
 *
 * @author: Sergei Krivorotov
 * @date: 1/9/2024
 */
public with sharing class AAS_AsyncActionUtils {

    public static Id enqueueJob(AAS_AsyncAction action) {
        AsyncOptions asyncOptions = new AsyncOptions();
        asyncOptions.maximumQueueableStackDepth = action.getAvailableAttempts();
        asyncOptions.minimumQueueableDelayInMinutes = action.getDelay();
        return System.enqueueJob(action, asyncOptions);
    }

    //Used to enqueue Async Action in separate transaction.
    public static void publishAsyncAction(AAS_AsyncAction action) {
        EventBus.publish(createAsyncEvent(action));
    }

    public static Async_Action__e createAsyncEvent(AAS_AsyncAction action) {
        return new Async_Action__e(
                Body__c = JSON.serialize(action),
                Type__c = action.getType().getName()
        );
    }

}